### ISSUE TITLE
Showing default resolution

### ISSUE THREAD

**Issue by vstath** [p00ya/displaymode#1] opened 2020-03-12 17:45 UTC
Hello, 

thank you for the nice utility. I did "displaymode d" and I cannot see the default resolution for my MacBook Pro 16. 

Also, why does the resolutions show multiple times? Does it have to do with the colors supported for the same resolution? 

Thanks!

**Comment by p00ya** [comment] 2020-03-14 13:59
> thank you for the nice utility. I did "displaymode d" and I cannot see the default resolution for my MacBook Pro 16.

Thanks for the report.  If none of the modes appear with the "*", then this means that the CoreGraphics framework isn't returning the current display mode in the list of modes that it thinks are supported by the display.  Which is weird (I don't see it with any of my devices).

To help me understand that, please try v1.2.0 (81cfb64) and reply back with:

1. the output from `displaymode d`
2. what you expect the current resolution to be
3. what version of macOS you're using (from  menu > About this Mac, something like "10.15.3 (19D76)").
4. anything interesting about your display setup (e.g. a secondary display connected, particular graphics card selected)

> Also, why does the resolutions show multiple times? Does it have to do with the colors supported for the same resolution?

In the case of the MacBook Pro 16", I'd guess that it's due to the multiple refresh rates supported, or maybe the dual graphics cards.  It could also be due to something different (e.g. colour depths like you mentioned).  v1.2.0 will check the refresh rate theory (it will print the refresh rates).

Edit: create a new v1.2.0 release

**Comment by vstath** [comment] 2020-03-17 05:27
v1.2.0 shows the internal monitor resolution fine, at the end of the list. 

My setup is MacOS Catalina 10.15.3

MacBook Pro 16 with dual GPU (Intel UHD 630 + AMD Radeon Pro 5500M), I have a 4k external monitor. 

Do you have plans to enable external monitor list / switch resolution (I'm not requesting, just wondering what the plans are). Also, is it possible to build the source without installing xcode etc? Never compiled any native mac binary so apologies if that's a noob question (I am a noob). 

As a last thing, thank you very much for your code and efforts. Very much appreciated.

**Comment by p00ya** [comment] 2020-03-18 22:11
Interesting.  Do you mind copy + pasting the full output from v1.2.0 into this thread? It would be useful for me to understand better what's going on.

> Do you have plans to enable external monitor list / switch resolution (I'm not requesting, just wondering what the plans are).

Good idea, I've opened #2 to track it.

> Also, is it possible to build the source without installing xcode etc? Never compiled any native mac binary so apologies if that's a noob question (I am a noob).

To compile from source, you will either need to install "Xcode command line tools" or Xcode.   Xcode command line tools is much smaller and I'd recommend it in your case.  There are instructions in `displaymode.c` for the `clang` command to run, and it should trigger a macOS prompt about downloading the command line tools.  But I'll also provide binaries in the "releases" section so you don't have to compile from source anyway. :)

You're very welcome, I'm glad displaymode is useful to you.

**Comment by p00ya** [comment] 2020-04-04 09:36
Figured out what was going on with the modes that could be current but weren't being returned by `CGDisplayCopyAllDisplayModes`.  This happens when a "scaled resolution" has been selected from System Preferences.

I haven't been able to reproduce duplicate modes (now that the refresh rates are being printed).  If you do see that happening, please open a new issue with the full output of `displaymode d`, since I'm closing this issue.

**Closed as completed by p00ya** 2020-04-04 09:36 UTC
